name: Docker Deployment

on:
  # release: 
  #   types: [published] 
 push:
   tags:
     - docker*

permissions:
  contents: read

jobs:
  deploy:
    name: Build and Push Docker
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      
      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build all Docker images
        run: sh ./docker/build.sh

      - name: Push all Docker images
        run: sh ./docker/push.sh
